### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by bclark2**
This solves an annoying problem 'Cannot read property 'length' of undefined
    at processResults'.

### CODE REVIEW

**Comment by EvanHahn** [comment]
This is a good PR. The only reason I hesitate: the content of the book will be different from what's here.

What do you think we should do?

**Comment by bclark2** [comment]
True, good book by the way. I suppose adding something to the readme about this particular chapter perhaps?

**Comment by EvanHahn** [comment]
Good idea.

I'll merge and add a README note.

**Comment by EvanHahn** [comment]
Thanks for your help!

**Pull request merged**
